name: Test

on:
  push:
    branches: [ main ] 

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Checkout
        uses: actions/checkout@v4
      - name: Install
        run: npm ci

      - name: Test
        run: npm t
